<?xml version="1.0" encoding="utf-8"?>
<Database Name="Recipes" Class="RecipeDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DELLLAPTOP\PATRICKSQLSERVE;Initial Catalog=Recipes;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Recipes" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CommonIngredient" Member="CommonIngredients">
    <Type Name="CommonIngredient">
      <Column Name="CommonIngredientID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="CommonBrand" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Association Name="CommonIngredient_Ingredient" Member="Ingredients" ThisKey="CommonIngredientID" OtherKey="CommonIngredientID" Type="Ingredient" />
    </Type>
  </Table>
  <Table Name="dbo.Steps" Member="Steps">
    <Type Name="Step">
      <Column Name="StepsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StepOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Instruction" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RecipeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Recipe_Step" Member="Recipe" ThisKey="RecipeID" OtherKey="RecipeID" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ingredient" Member="Ingredients">
    <Type Name="Ingredient">
      <Column Name="IngredientsID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CommonIngredientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeasurementUnitID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ammount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RecipeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CommonIngredient_Ingredient" Member="CommonIngredient" ThisKey="CommonIngredientID" OtherKey="CommonIngredientID" Type="CommonIngredient" IsForeignKey="true" />
      <Association Name="MeasurementUnit_Ingredient" Member="MeasurementUnit" ThisKey="MeasurementUnitID" OtherKey="MeasurementUnitID" Type="MeasurementUnit" IsForeignKey="true" />
      <Association Name="Recipe_Ingredient" Member="Recipe" ThisKey="RecipeID" OtherKey="RecipeID" Type="Recipe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeasurementUnit" Member="MeasurementUnits">
    <Type Name="MeasurementUnit">
      <Column Name="MeasurementUnitID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SSIUnit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SSIConversion" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="MeasurementUnit_Ingredient" Member="Ingredients" ThisKey="MeasurementUnitID" OtherKey="MeasurementUnitID" Type="Ingredient" />
    </Type>
  </Table>
  <Table Name="dbo.Recipe" Member="Recipes">
    <Type Name="Recipe">
      <Column Name="RecipeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SoruceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Recipe_Step" Member="Steps" ThisKey="RecipeID" OtherKey="RecipeID" Type="Step" />
      <Association Name="Recipe_Ingredient" Member="Ingredients" ThisKey="RecipeID" OtherKey="RecipeID" Type="Ingredient" />
      <Association Name="Source_Recipe" Member="Source" ThisKey="SoruceID" OtherKey="SourceID" Type="Source" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Source" Member="Sources">
    <Type Name="Source">
      <Column Name="SourceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Source_Recipe" Member="Recipes" ThisKey="SourceID" OtherKey="SoruceID" Type="Recipe" />
    </Type>
  </Table>
</Database>