//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $rootnamespace$.$fileinputname$.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("$rootnamespace$.$fileinputname$.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        internal static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevant information about $fileinputname$..
        /// </summary>
        internal static string AdditionalInfoNote {
            get {
                return ResourceManager.GetString("AdditionalInfoNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From here you can manage categories..
        /// </summary>
        internal static string CategoriesView_Description {
            get {
                return ResourceManager.GetString("CategoriesView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string CategoriesView_Title {
            get {
                return ResourceManager.GetString("CategoriesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows one to edit $fileinputname$..
        /// </summary>
        internal static string $fileinputname$EditView_Description {
            get {
                return ResourceManager.GetString("$fileinputname$EditView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit $fileinputname$.
        /// </summary>
        internal static string $fileinputname$EditView_Title {
            get {
                return ResourceManager.GetString("$fileinputname$EditView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides list of $fileinputname$ versions and ability to rollback to previous version..
        /// </summary>
        internal static string $fileinputname$HistoryView_Description {
            get {
                return ResourceManager.GetString("$fileinputname$HistoryView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $fileinputname$ history.
        /// </summary>
        internal static string $fileinputname$HistoryView_Title {
            get {
                return ResourceManager.GetString("$fileinputname$HistoryView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows one to create new $fileinputname$..
        /// </summary>
        internal static string $fileinputname$NewView_Description {
            get {
                return ResourceManager.GetString("$fileinputname$NewView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new $fileinputname$.
        /// </summary>
        internal static string $fileinputname$NewView_Title {
            get {
                return ResourceManager.GetString("$fileinputname$NewView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the preview of the $fileinputname$ item..
        /// </summary>
        internal static string $fileinputname$PreviewView_Description {
            get {
                return ResourceManager.GetString("$fileinputname$PreviewView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview $fileinputname$.
        /// </summary>
        internal static string $fileinputname$PreviewView_Title {
            get {
                return ResourceManager.GetString("$fileinputname$PreviewView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the list of all $fileinputname$..
        /// </summary>
        internal static string $fileinputname$ItemListView_Description {
            get {
                return ResourceManager.GetString("$fileinputname$ItemListView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $fileinputname$ items.
        /// </summary>
        internal static string $fileinputname$ItemListView_Title {
            get {
                return ResourceManager.GetString("$fileinputname$ItemListView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public control for displaying $fileinputname$..
        /// </summary>
        internal static string $fileinputname$PublicView_Description {
            get {
                return ResourceManager.GetString("$fileinputname$PublicView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $fileinputname$ View.
        /// </summary>
        internal static string $fileinputname$PublicView_DisplayName {
            get {
                return ResourceManager.GetString("$fileinputname$PublicView_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From here you can manage all your $fileinputname$..
        /// </summary>
        internal static string $fileinputname$View_Description {
            get {
                return ResourceManager.GetString("$fileinputname$View_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $fileinputname$.
        /// </summary>
        internal static string $fileinputname$View_Title {
            get {
                return ResourceManager.GetString("$fileinputname$View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From here you can manage permissions..
        /// </summary>
        internal static string PermissionsView_Description {
            get {
                return ResourceManager.GetString("PermissionsView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string PermissionsView_Title {
            get {
                return ResourceManager.GetString("PermissionsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From here you can manage tags..
        /// </summary>
        internal static string TagsView_Description {
            get {
                return ResourceManager.GetString("TagsView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string TagsView_Title {
            get {
                return ResourceManager.GetString("TagsView_Title", resourceCulture);
            }
        }
    }
}
